//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package aggregated

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AggregatedEnvironmentStatus) DeepCopyInto(out *AggregatedEnvironmentStatus) {
	*out = *in
	out.ActiveCommit = in.ActiveCommit
	if in.ProposedCommit != nil {
		in, out := &in.ProposedCommit, &out.ProposedCommit
		*out = new(CommitInfo)
		**out = **in
	}
	if in.PullRequest != nil {
		in, out := &in.PullRequest, &out.PullRequest
		*out = new(PullRequestInfo)
		**out = **in
	}
	if in.CommitStatuses != nil {
		in, out := &in.CommitStatuses, &out.CommitStatuses
		*out = make([]CommitStatusInfo, len(*in))
		copy(*out, *in)
	}
	if in.ChangeTransferPolicies != nil {
		in, out := &in.ChangeTransferPolicies, &out.ChangeTransferPolicies
		*out = make([]ChangeTransferPolicyInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AggregatedEnvironmentStatus.
func (in *AggregatedEnvironmentStatus) DeepCopy() *AggregatedEnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(AggregatedEnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChangeTransferPolicyInfo) DeepCopyInto(out *ChangeTransferPolicyInfo) {
	*out = *in
	if in.ActiveCommitStatuses != nil {
		in, out := &in.ActiveCommitStatuses, &out.ActiveCommitStatuses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ProposedCommitStatuses != nil {
		in, out := &in.ProposedCommitStatuses, &out.ProposedCommitStatuses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChangeTransferPolicyInfo.
func (in *ChangeTransferPolicyInfo) DeepCopy() *ChangeTransferPolicyInfo {
	if in == nil {
		return nil
	}
	out := new(ChangeTransferPolicyInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommitInfo) DeepCopyInto(out *CommitInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommitInfo.
func (in *CommitInfo) DeepCopy() *CommitInfo {
	if in == nil {
		return nil
	}
	out := new(CommitInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommitStatusInfo) DeepCopyInto(out *CommitStatusInfo) {
	*out = *in
	out.Source = in.Source
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommitStatusInfo.
func (in *CommitStatusInfo) DeepCopy() *CommitStatusInfo {
	if in == nil {
		return nil
	}
	out := new(CommitStatusInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommitStatusSource) DeepCopyInto(out *CommitStatusSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommitStatusSource.
func (in *CommitStatusSource) DeepCopy() *CommitStatusSource {
	if in == nil {
		return nil
	}
	out := new(CommitStatusSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectReference) DeepCopyInto(out *ObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectReference.
func (in *ObjectReference) DeepCopy() *ObjectReference {
	if in == nil {
		return nil
	}
	out := new(ObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromotionStatus) DeepCopyInto(out *PromotionStatus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromotionStatus.
func (in *PromotionStatus) DeepCopy() *PromotionStatus {
	if in == nil {
		return nil
	}
	out := new(PromotionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PromotionStatus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromotionStatusList) DeepCopyInto(out *PromotionStatusList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PromotionStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromotionStatusList.
func (in *PromotionStatusList) DeepCopy() *PromotionStatusList {
	if in == nil {
		return nil
	}
	out := new(PromotionStatusList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PromotionStatusList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromotionStatusSpec) DeepCopyInto(out *PromotionStatusSpec) {
	*out = *in
	out.PromotionStrategyRef = in.PromotionStrategyRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromotionStatusSpec.
func (in *PromotionStatusSpec) DeepCopy() *PromotionStatusSpec {
	if in == nil {
		return nil
	}
	out := new(PromotionStatusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromotionStatusStatus) DeepCopyInto(out *PromotionStatusStatus) {
	*out = *in
	if in.Environments != nil {
		in, out := &in.Environments, &out.Environments
		*out = make([]AggregatedEnvironmentStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromotionStatusStatus.
func (in *PromotionStatusStatus) DeepCopy() *PromotionStatusStatus {
	if in == nil {
		return nil
	}
	out := new(PromotionStatusStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PullRequestInfo) DeepCopyInto(out *PullRequestInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PullRequestInfo.
func (in *PullRequestInfo) DeepCopy() *PullRequestInfo {
	if in == nil {
		return nil
	}
	out := new(PullRequestInfo)
	in.DeepCopyInto(out)
	return out
}
