/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.21. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/argoproj-labs/gitops-promoter/api/v1alpha1"
)

// ChangeTransferPolicySpecApplyConfiguration represents a declarative configuration of the ChangeTransferPolicySpec type for use
// with apply.
//
// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.
// ChangeTransferPolicySpec defines the desired state of ChangeTransferPolicy
type ChangeTransferPolicySpecApplyConfiguration struct {
	// RepositoryReference what repository to open the PR on.
	RepositoryReference *ObjectReferenceApplyConfiguration `json:"gitRepositoryRef,omitempty"`
	// ProposedBranch staging hydrated branch
	// Must not start with '-', contain ':', or contain '..'.
	ProposedBranch *string `json:"proposedBranch,omitempty"`
	// ActiveBranch staging hydrated branch
	// Must not start with '-', contain ':', or contain '..'.
	ActiveBranch *string `json:"activeBranch,omitempty"`
	// ActivePath is an optional repository subpath for this policy's active state.
	// When set, hydrator metadata is read from <activePath>/hydrator.metadata.
	ActivePath *string `json:"activePath,omitempty"`
	AutoMerge  *bool   `json:"autoMerge,omitempty"`
	// ActiveCommitStatuses lists the statuses to be monitored on the active branch
	ActiveCommitStatuses []CommitStatusSelectorApplyConfiguration `json:"activeCommitStatuses,omitempty"`
	// ProposedCommitStatuses lists the statuses to be monitored on the proposed branch
	ProposedCommitStatuses []CommitStatusSelectorApplyConfiguration `json:"proposedCommitStatuses,omitempty"`
	// PullRequest configures SCM pull request behavior for this change transfer policy.
	// Copied from the owning PromotionStrategy by the PromotionStrategy controller.
	PullRequest *PullRequestPolicySpecApplyConfiguration `json:"pullRequest,omitempty"`
	// PromotionPolicy selects which candidate on the proposed branch this policy promotes.
	// Copied from the owning PromotionStrategy by the PromotionStrategy controller. Empty means Latest.
	PromotionPolicy *apiv1alpha1.PromotionPolicy `json:"promotionPolicy,omitempty"`
	// PromotionBranch is a promoter-owned branch that carries the candidate this policy has selected
	// for promotion. It is required by every policy other than Latest, which promotes the proposed
	// branch tip directly and needs no separate branch.
	//
	// The proposed branch belongs to the hydrator and always tracks the newest dry commit, so it cannot
	// be used to promote anything but the newest candidate. Instead the controller picks a commit out
	// of the proposed branch's history and force-pushes it here, and the promotion pull request is
	// opened from this branch. Nothing but this controller may write to it.
	//
	// Must not start with '-', contain ':', or contain '..'.
	PromotionBranch *string `json:"promotionBranch,omitempty"`
	// Candidates constrains which hydrated changes this policy may promote. It is computed by the
	// PromotionStrategy controller from the verification ledgers of every preceding environment.
	// A nil value means unconstrained, which is the case for the first environment in a sequence
	// because it has no preceding environment to wait for.
	Candidates *PromotionCandidatesApplyConfiguration `json:"candidates,omitempty"`
}

// ChangeTransferPolicySpecApplyConfiguration constructs a declarative configuration of the ChangeTransferPolicySpec type for use with
// apply.
func ChangeTransferPolicySpec() *ChangeTransferPolicySpecApplyConfiguration {
	return &ChangeTransferPolicySpecApplyConfiguration{}
}

// WithRepositoryReference sets the RepositoryReference field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RepositoryReference field is set to the value of the last call.
func (b *ChangeTransferPolicySpecApplyConfiguration) WithRepositoryReference(value *ObjectReferenceApplyConfiguration) *ChangeTransferPolicySpecApplyConfiguration {
	b.RepositoryReference = value
	return b
}

// WithProposedBranch sets the ProposedBranch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProposedBranch field is set to the value of the last call.
func (b *ChangeTransferPolicySpecApplyConfiguration) WithProposedBranch(value string) *ChangeTransferPolicySpecApplyConfiguration {
	b.ProposedBranch = &value
	return b
}

// WithActiveBranch sets the ActiveBranch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActiveBranch field is set to the value of the last call.
func (b *ChangeTransferPolicySpecApplyConfiguration) WithActiveBranch(value string) *ChangeTransferPolicySpecApplyConfiguration {
	b.ActiveBranch = &value
	return b
}

// WithActivePath sets the ActivePath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActivePath field is set to the value of the last call.
func (b *ChangeTransferPolicySpecApplyConfiguration) WithActivePath(value string) *ChangeTransferPolicySpecApplyConfiguration {
	b.ActivePath = &value
	return b
}

// WithAutoMerge sets the AutoMerge field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AutoMerge field is set to the value of the last call.
func (b *ChangeTransferPolicySpecApplyConfiguration) WithAutoMerge(value bool) *ChangeTransferPolicySpecApplyConfiguration {
	b.AutoMerge = &value
	return b
}

// WithActiveCommitStatuses adds the given value to the ActiveCommitStatuses field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ActiveCommitStatuses field.
func (b *ChangeTransferPolicySpecApplyConfiguration) WithActiveCommitStatuses(values ...*CommitStatusSelectorApplyConfiguration) *ChangeTransferPolicySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithActiveCommitStatuses")
		}
		b.ActiveCommitStatuses = append(b.ActiveCommitStatuses, *values[i])
	}
	return b
}

// WithProposedCommitStatuses adds the given value to the ProposedCommitStatuses field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ProposedCommitStatuses field.
func (b *ChangeTransferPolicySpecApplyConfiguration) WithProposedCommitStatuses(values ...*CommitStatusSelectorApplyConfiguration) *ChangeTransferPolicySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithProposedCommitStatuses")
		}
		b.ProposedCommitStatuses = append(b.ProposedCommitStatuses, *values[i])
	}
	return b
}

// WithPullRequest sets the PullRequest field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PullRequest field is set to the value of the last call.
func (b *ChangeTransferPolicySpecApplyConfiguration) WithPullRequest(value *PullRequestPolicySpecApplyConfiguration) *ChangeTransferPolicySpecApplyConfiguration {
	b.PullRequest = value
	return b
}

// WithPromotionPolicy sets the PromotionPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PromotionPolicy field is set to the value of the last call.
func (b *ChangeTransferPolicySpecApplyConfiguration) WithPromotionPolicy(value apiv1alpha1.PromotionPolicy) *ChangeTransferPolicySpecApplyConfiguration {
	b.PromotionPolicy = &value
	return b
}

// WithPromotionBranch sets the PromotionBranch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PromotionBranch field is set to the value of the last call.
func (b *ChangeTransferPolicySpecApplyConfiguration) WithPromotionBranch(value string) *ChangeTransferPolicySpecApplyConfiguration {
	b.PromotionBranch = &value
	return b
}

// WithCandidates sets the Candidates field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Candidates field is set to the value of the last call.
func (b *ChangeTransferPolicySpecApplyConfiguration) WithCandidates(value *PromotionCandidatesApplyConfiguration) *ChangeTransferPolicySpecApplyConfiguration {
	b.Candidates = value
	return b
}
