/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

// DagCommitStatusSpecApplyConfiguration represents a declarative configuration of the DagCommitStatusSpec type for use
// with apply.
//
// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.
// DagCommitStatusSpec defines the desired state of DagCommitStatus.
//
// A DagCommitStatus declares a directed-acyclic dependency graph over the
// environments of a referenced PromotionStrategy. For each non-root environment
// in the graph, the controller produces one CommitStatus on that environment's
// proposed hydrated SHA, whose phase aggregates the active CommitStatuses on the
// parent (dependsOn) environments. Users opt in to gating by referencing the
// produced CommitStatus's Key in the PromotionStrategy's proposedCommitStatuses.
type DagCommitStatusSpecApplyConfiguration struct {
	// PromotionStrategyRef is a reference to the PromotionStrategy whose environments
	// are being graphed. Must live in the same namespace as this DagCommitStatus.
	PromotionStrategyRef *ObjectReferenceApplyConfiguration `json:"promotionStrategyRef,omitempty"`
	// Key is the CommitStatus key produced on each non-root environment's proposed
	// hydrated SHA, and the key users reference in proposedCommitStatuses to gate
	// promotion. Defaults to "promoter-previous-environment" for back-compat with
	// the synthesised gate that PromotionStrategy used to produce.
	Key *string `json:"key,omitempty"`
	// Environments declares the dependency graph. Every branch named here must
	// exist in the referenced PromotionStrategy's spec.environments. Every entry
	// in dependsOn must also appear in this list. Cycles are rejected.
	Environments []DagEnvironmentApplyConfiguration `json:"environments,omitempty"`
}

// DagCommitStatusSpecApplyConfiguration constructs a declarative configuration of the DagCommitStatusSpec type for use with
// apply.
func DagCommitStatusSpec() *DagCommitStatusSpecApplyConfiguration {
	return &DagCommitStatusSpecApplyConfiguration{}
}

// WithPromotionStrategyRef sets the PromotionStrategyRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PromotionStrategyRef field is set to the value of the last call.
func (b *DagCommitStatusSpecApplyConfiguration) WithPromotionStrategyRef(value *ObjectReferenceApplyConfiguration) *DagCommitStatusSpecApplyConfiguration {
	b.PromotionStrategyRef = value
	return b
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *DagCommitStatusSpecApplyConfiguration) WithKey(value string) *DagCommitStatusSpecApplyConfiguration {
	b.Key = &value
	return b
}

// WithEnvironments adds the given value to the Environments field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Environments field.
func (b *DagCommitStatusSpecApplyConfiguration) WithEnvironments(values ...*DagEnvironmentApplyConfiguration) *DagCommitStatusSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithEnvironments")
		}
		b.Environments = append(b.Environments, *values[i])
	}
	return b
}
