/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

// DagEnvironmentApplyConfiguration represents a declarative configuration of the DagEnvironment type for use
// with apply.
//
// DagEnvironment is one node in the DAG.
type DagEnvironmentApplyConfiguration struct {
	// Branch is the active branch of the environment in the referenced PromotionStrategy.
	Branch *string `json:"branch,omitempty"`
	// DependsOn lists the parent branches that must be healthy before this
	// environment's promotion is gated as successful. An empty (or absent)
	// DependsOn means this is a root environment in the graph and no
	// CommitStatus is produced for it.
	DependsOn []string `json:"dependsOn,omitempty"`
}

// DagEnvironmentApplyConfiguration constructs a declarative configuration of the DagEnvironment type for use with
// apply.
func DagEnvironment() *DagEnvironmentApplyConfiguration {
	return &DagEnvironmentApplyConfiguration{}
}

// WithBranch sets the Branch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Branch field is set to the value of the last call.
func (b *DagEnvironmentApplyConfiguration) WithBranch(value string) *DagEnvironmentApplyConfiguration {
	b.Branch = &value
	return b
}

// WithDependsOn adds the given value to the DependsOn field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DependsOn field.
func (b *DagEnvironmentApplyConfiguration) WithDependsOn(values ...string) *DagEnvironmentApplyConfiguration {
	for i := range values {
		b.DependsOn = append(b.DependsOn, values[i])
	}
	return b
}
