/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/argoproj-labs/gitops-promoter/api/v1alpha1"
)

// DagEnvironmentStatusApplyConfiguration represents a declarative configuration of the DagEnvironmentStatus type for use
// with apply.
//
// DagEnvironmentStatus is the per-non-root-env aggregation result.
type DagEnvironmentStatusApplyConfiguration struct {
	// Branch is the gated (child) environment.
	Branch *string `json:"branch,omitempty"`
	// AggregatePhase is the phase written to the produced CommitStatus on this env's
	// proposed hydrated SHA (success only when all parent chains are success).
	AggregatePhase *apiv1alpha1.CommitStatusPhase `json:"aggregatePhase,omitempty"`
	// DrySha is the dry SHA that the parents were evaluated against, i.e. the
	// gated environment's effective hydrated dry SHA.
	DrySha *string `json:"drySha,omitempty"`
	// Parents carries the per-parent disaggregated view: for each dependsOn branch,
	// which active CommitStatuses contributed and their individual phases.
	Parents []DagParentStatusApplyConfiguration `json:"parents,omitempty"`
}

// DagEnvironmentStatusApplyConfiguration constructs a declarative configuration of the DagEnvironmentStatus type for use with
// apply.
func DagEnvironmentStatus() *DagEnvironmentStatusApplyConfiguration {
	return &DagEnvironmentStatusApplyConfiguration{}
}

// WithBranch sets the Branch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Branch field is set to the value of the last call.
func (b *DagEnvironmentStatusApplyConfiguration) WithBranch(value string) *DagEnvironmentStatusApplyConfiguration {
	b.Branch = &value
	return b
}

// WithAggregatePhase sets the AggregatePhase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AggregatePhase field is set to the value of the last call.
func (b *DagEnvironmentStatusApplyConfiguration) WithAggregatePhase(value apiv1alpha1.CommitStatusPhase) *DagEnvironmentStatusApplyConfiguration {
	b.AggregatePhase = &value
	return b
}

// WithDrySha sets the DrySha field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DrySha field is set to the value of the last call.
func (b *DagEnvironmentStatusApplyConfiguration) WithDrySha(value string) *DagEnvironmentStatusApplyConfiguration {
	b.DrySha = &value
	return b
}

// WithParents adds the given value to the Parents field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Parents field.
func (b *DagEnvironmentStatusApplyConfiguration) WithParents(values ...*DagParentStatusApplyConfiguration) *DagEnvironmentStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithParents")
		}
		b.Parents = append(b.Parents, *values[i])
	}
	return b
}
