/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/argoproj-labs/gitops-promoter/api/v1alpha1"
)

// DagParentStatusApplyConfiguration represents a declarative configuration of the DagParentStatus type for use
// with apply.
//
// DagParentStatus is the per-parent disaggregated view of contributing active commit statuses.
type DagParentStatusApplyConfiguration struct {
	// Branch is the dependsOn parent.
	Branch *string `json:"branch,omitempty"`
	// Phase is this parent's rolled-up phase (worst over its CommitStatuses + chain).
	Phase *apiv1alpha1.CommitStatusPhase `json:"phase,omitempty"`
	// CommitStatuses is the disaggregated list of active CommitStatuses on this parent
	// for the matched dry SHA.
	CommitStatuses []ChangeRequestPolicyCommitStatusPhaseApplyConfiguration `json:"commitStatuses,omitempty"`
}

// DagParentStatusApplyConfiguration constructs a declarative configuration of the DagParentStatus type for use with
// apply.
func DagParentStatus() *DagParentStatusApplyConfiguration {
	return &DagParentStatusApplyConfiguration{}
}

// WithBranch sets the Branch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Branch field is set to the value of the last call.
func (b *DagParentStatusApplyConfiguration) WithBranch(value string) *DagParentStatusApplyConfiguration {
	b.Branch = &value
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *DagParentStatusApplyConfiguration) WithPhase(value apiv1alpha1.CommitStatusPhase) *DagParentStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithCommitStatuses adds the given value to the CommitStatuses field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CommitStatuses field.
func (b *DagParentStatusApplyConfiguration) WithCommitStatuses(values ...*ChangeRequestPolicyCommitStatusPhaseApplyConfiguration) *DagParentStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithCommitStatuses")
		}
		b.CommitStatuses = append(b.CommitStatuses, *values[i])
	}
	return b
}
