/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.22. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/argoproj-labs/gitops-promoter/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DryShaSuccessfulCommitStatusEnvironmentStatusApplyConfiguration represents a declarative configuration of the DryShaSuccessfulCommitStatusEnvironmentStatus type for use
// with apply.
//
// DryShaSuccessfulCommitStatusEnvironmentStatus defines observed state for one environment branch.
type DryShaSuccessfulCommitStatusEnvironmentStatusApplyConfiguration struct {
	// Branch is the environment branch name.
	Branch *string `json:"branch,omitempty"`
	// Gate report fields (phase, description, url, reportedSha) mirror the child CommitStatus spec.
	// When there is no in-flight proposed change, the controller copies the last child CommitStatus
	// report instead of re-evaluating the gate.
	GateEnvironmentCommitStatusApplyConfiguration `json:""`
	// RebuiltFromSha is the active branch tip that dryShaHistory was walked from. While the environment's
	// live active hydrated SHA still equals this, the cached record is current and no git work is done.
	RebuiltFromSha *string `json:"rebuiltFromSha,omitempty"`
	// RebuiltAt is when the active branch walk that produced dryShaHistory last ran.
	RebuiltAt *v1.Time `json:"rebuiltAt,omitempty"`
	// DryShaHistory is a cache of the dry commits this environment has run, newest first: index 0 is
	// closest to the active branch tip. It is rebuilt from the promotion-history git notes on the active
	// branch and is safe to delete — the next reconcile regenerates it from git.
	DryShaHistory []DryShaRecordApplyConfiguration `json:"dryShaHistory,omitempty"`
	// Upstreams lists all transitive ancestor branches and whether each is satisfied for this
	// environment's promotion target.
	Upstreams []DryShaSuccessfulCommitStatusUpstreamStatusApplyConfiguration `json:"upstreams,omitempty"`
}

// DryShaSuccessfulCommitStatusEnvironmentStatusApplyConfiguration constructs a declarative configuration of the DryShaSuccessfulCommitStatusEnvironmentStatus type for use with
// apply.
func DryShaSuccessfulCommitStatusEnvironmentStatus() *DryShaSuccessfulCommitStatusEnvironmentStatusApplyConfiguration {
	return &DryShaSuccessfulCommitStatusEnvironmentStatusApplyConfiguration{}
}

// WithBranch sets the Branch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Branch field is set to the value of the last call.
func (b *DryShaSuccessfulCommitStatusEnvironmentStatusApplyConfiguration) WithBranch(value string) *DryShaSuccessfulCommitStatusEnvironmentStatusApplyConfiguration {
	b.Branch = &value
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *DryShaSuccessfulCommitStatusEnvironmentStatusApplyConfiguration) WithPhase(value apiv1alpha1.CommitStatusPhase) *DryShaSuccessfulCommitStatusEnvironmentStatusApplyConfiguration {
	b.GateEnvironmentCommitStatusApplyConfiguration.Phase = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *DryShaSuccessfulCommitStatusEnvironmentStatusApplyConfiguration) WithDescription(value string) *DryShaSuccessfulCommitStatusEnvironmentStatusApplyConfiguration {
	b.GateEnvironmentCommitStatusApplyConfiguration.Description = &value
	return b
}

// WithUrl sets the Url field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Url field is set to the value of the last call.
func (b *DryShaSuccessfulCommitStatusEnvironmentStatusApplyConfiguration) WithUrl(value string) *DryShaSuccessfulCommitStatusEnvironmentStatusApplyConfiguration {
	b.GateEnvironmentCommitStatusApplyConfiguration.Url = &value
	return b
}

// WithReportedSha sets the ReportedSha field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReportedSha field is set to the value of the last call.
func (b *DryShaSuccessfulCommitStatusEnvironmentStatusApplyConfiguration) WithReportedSha(value string) *DryShaSuccessfulCommitStatusEnvironmentStatusApplyConfiguration {
	b.GateEnvironmentCommitStatusApplyConfiguration.ReportedSha = &value
	return b
}

// WithRebuiltFromSha sets the RebuiltFromSha field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RebuiltFromSha field is set to the value of the last call.
func (b *DryShaSuccessfulCommitStatusEnvironmentStatusApplyConfiguration) WithRebuiltFromSha(value string) *DryShaSuccessfulCommitStatusEnvironmentStatusApplyConfiguration {
	b.RebuiltFromSha = &value
	return b
}

// WithRebuiltAt sets the RebuiltAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RebuiltAt field is set to the value of the last call.
func (b *DryShaSuccessfulCommitStatusEnvironmentStatusApplyConfiguration) WithRebuiltAt(value v1.Time) *DryShaSuccessfulCommitStatusEnvironmentStatusApplyConfiguration {
	b.RebuiltAt = &value
	return b
}

// WithDryShaHistory adds the given value to the DryShaHistory field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DryShaHistory field.
func (b *DryShaSuccessfulCommitStatusEnvironmentStatusApplyConfiguration) WithDryShaHistory(values ...*DryShaRecordApplyConfiguration) *DryShaSuccessfulCommitStatusEnvironmentStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithDryShaHistory")
		}
		b.DryShaHistory = append(b.DryShaHistory, *values[i])
	}
	return b
}

// WithUpstreams adds the given value to the Upstreams field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Upstreams field.
func (b *DryShaSuccessfulCommitStatusEnvironmentStatusApplyConfiguration) WithUpstreams(values ...*DryShaSuccessfulCommitStatusUpstreamStatusApplyConfiguration) *DryShaSuccessfulCommitStatusEnvironmentStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithUpstreams")
		}
		b.Upstreams = append(b.Upstreams, *values[i])
	}
	return b
}
