/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.22. DO NOT EDIT.

package v1alpha1

// DryShaSuccessfulCommitStatusUpstreamStatusApplyConfiguration represents a declarative configuration of the DryShaSuccessfulCommitStatusUpstreamStatus type for use
// with apply.
//
// DryShaSuccessfulCommitStatusUpstreamStatus reports whether a transitive upstream branch is satisfied
// for this environment's promotion target.
type DryShaSuccessfulCommitStatusUpstreamStatusApplyConfiguration struct {
	// Branch is the upstream environment branch name.
	Branch *string `json:"branch,omitempty"`
	// SatisfiedBySha is the dry commit whose recorded success satisfied this upstream. It equals the
	// target dry SHA for an exact match, or a descendant dry SHA when spec.allowNewerDrySha applies.
	// Omitted when the upstream is not satisfied.
	SatisfiedBySha *string `json:"satisfiedBySha,omitempty"`
	// Reason explains the verdict for this upstream. It is normally set only when the upstream is not
	// satisfied, but a satisfied upstream also carries one when it was skipped because the proposed dry
	// commit renders no change there (a no-op hydration), since nothing in dryShaHistory records that.
	Reason *string `json:"reason,omitempty"`
	// Satisfied is true when the upstream has been successful for this environment's target dry SHA.
	Satisfied *bool `json:"satisfied,omitempty"`
}

// DryShaSuccessfulCommitStatusUpstreamStatusApplyConfiguration constructs a declarative configuration of the DryShaSuccessfulCommitStatusUpstreamStatus type for use with
// apply.
func DryShaSuccessfulCommitStatusUpstreamStatus() *DryShaSuccessfulCommitStatusUpstreamStatusApplyConfiguration {
	return &DryShaSuccessfulCommitStatusUpstreamStatusApplyConfiguration{}
}

// WithBranch sets the Branch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Branch field is set to the value of the last call.
func (b *DryShaSuccessfulCommitStatusUpstreamStatusApplyConfiguration) WithBranch(value string) *DryShaSuccessfulCommitStatusUpstreamStatusApplyConfiguration {
	b.Branch = &value
	return b
}

// WithSatisfiedBySha sets the SatisfiedBySha field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SatisfiedBySha field is set to the value of the last call.
func (b *DryShaSuccessfulCommitStatusUpstreamStatusApplyConfiguration) WithSatisfiedBySha(value string) *DryShaSuccessfulCommitStatusUpstreamStatusApplyConfiguration {
	b.SatisfiedBySha = &value
	return b
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *DryShaSuccessfulCommitStatusUpstreamStatusApplyConfiguration) WithReason(value string) *DryShaSuccessfulCommitStatusUpstreamStatusApplyConfiguration {
	b.Reason = &value
	return b
}

// WithSatisfied sets the Satisfied field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Satisfied field is set to the value of the last call.
func (b *DryShaSuccessfulCommitStatusUpstreamStatusApplyConfiguration) WithSatisfied(value bool) *DryShaSuccessfulCommitStatusUpstreamStatusApplyConfiguration {
	b.Satisfied = &value
	return b
}
