/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.22. DO NOT EDIT.

package v1alpha1

// DryShaSuccessfulCommitStatusSpecApplyConfiguration represents a declarative configuration of the DryShaSuccessfulCommitStatusSpec type for use
// with apply.
//
// DryShaSuccessfulCommitStatusSpec defines the desired state of DryShaSuccessfulCommitStatus.
type DryShaSuccessfulCommitStatusSpecApplyConfiguration struct {
	// PromotionStrategyRef is a reference to the promotion strategy that this gate applies to. The controller
	// watches this PromotionStrategy and, for each environment, reports whether the dry commit being promoted
	// has already been successful in that environment's upstream (dependsOn) environments.
	PromotionStrategyRef *ObjectReferenceApplyConfiguration `json:"promotionStrategyRef,omitempty"`
	// Key is the commit status key this controller writes on each environment's proposed hydrated SHA.
	// The PromotionStrategy controller injects this key onto every ChangeTransferPolicy's proposedCommitStatuses.
	// Must be lowercase alphanumeric with hyphens, 1–63 characters (pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$).
	Key *string `json:"key,omitempty"`
	// URL generates the URL to use on the per-environment CommitStatus (SCM details link), for
	// example a link into the Promoter UI that highlights this environment's dependsOn upstreams.
	// Optional; when empty, no URL is set on the child CommitStatus. The template receives
	// .Environment, .DryShaSuccessfulCommitStatus, .PromotionStrategy, .DependsOn, and .DependsOnQuery
	// (see controller docs).
	URL *URLConfigApplyConfiguration `json:"url,omitempty"`
	// HistoryDepth is how many first-parent commits of each environment's active branch are walked when
	// rebuilding the dry SHA record from the promotion-history git notes. A dry commit older than this
	// depth is not found in the record and the gate reports pending for it.
	HistoryDepth *int32 `json:"historyDepth,omitempty"`
}

// DryShaSuccessfulCommitStatusSpecApplyConfiguration constructs a declarative configuration of the DryShaSuccessfulCommitStatusSpec type for use with
// apply.
func DryShaSuccessfulCommitStatusSpec() *DryShaSuccessfulCommitStatusSpecApplyConfiguration {
	return &DryShaSuccessfulCommitStatusSpecApplyConfiguration{}
}

// WithPromotionStrategyRef sets the PromotionStrategyRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PromotionStrategyRef field is set to the value of the last call.
func (b *DryShaSuccessfulCommitStatusSpecApplyConfiguration) WithPromotionStrategyRef(value *ObjectReferenceApplyConfiguration) *DryShaSuccessfulCommitStatusSpecApplyConfiguration {
	b.PromotionStrategyRef = value
	return b
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *DryShaSuccessfulCommitStatusSpecApplyConfiguration) WithKey(value string) *DryShaSuccessfulCommitStatusSpecApplyConfiguration {
	b.Key = &value
	return b
}

// WithURL sets the URL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URL field is set to the value of the last call.
func (b *DryShaSuccessfulCommitStatusSpecApplyConfiguration) WithURL(value *URLConfigApplyConfiguration) *DryShaSuccessfulCommitStatusSpecApplyConfiguration {
	b.URL = value
	return b
}

// WithHistoryDepth sets the HistoryDepth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HistoryDepth field is set to the value of the last call.
func (b *DryShaSuccessfulCommitStatusSpecApplyConfiguration) WithHistoryDepth(value int32) *DryShaSuccessfulCommitStatusSpecApplyConfiguration {
	b.HistoryDepth = &value
	return b
}
