/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.22. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/argoproj-labs/gitops-promoter/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DryShaRecordApplyConfiguration represents a declarative configuration of the DryShaRecord type for use
// with apply.
//
// DryShaRecord is one entry of an environment's dry SHA record, reconstructed from its active branch.
type DryShaRecordApplyConfiguration struct {
	// Sha is the dry commit that was running in the environment. For a git-derived entry this is the
	// promotion-history note's Sha-dry-active trailer, which records what the environment was running
	// immediately before that promotion merged.
	// Supports both SHA-1 (40 chars) and SHA-256 (64 chars) Git hash formats.
	Sha *string `json:"sha,omitempty"`
	// MergeSha is the active branch commit this entry was derived from. Entries are ordered by
	// first-parent distance from the branch tip, so it doubles as the entry's position marker.
	// For a live entry it is the environment's active hydrated SHA.
	MergeSha *string `json:"mergeSha,omitempty"`
	// Source names which git source supplied this entry's data.
	Source *apiv1alpha1.DryShaRecordSource `json:"source,omitempty"`
	// MergedAt is the merge time of the promotion that produced this entry (the note's
	// Pull-request-merge-time trailer). Informational; ordering uses the first-parent walk, not time.
	MergedAt *v1.Time `json:"mergedAt,omitempty"`
	// Successful is true when every active commit status recorded alongside Sha was successful. This is
	// the same success criterion DependentsSuccessfulCommitStatus applies to an upstream environment,
	// read from the recorded snapshot rather than from live state.
	Successful *bool `json:"successful,omitempty"`
}

// DryShaRecordApplyConfiguration constructs a declarative configuration of the DryShaRecord type for use with
// apply.
func DryShaRecord() *DryShaRecordApplyConfiguration {
	return &DryShaRecordApplyConfiguration{}
}

// WithSha sets the Sha field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Sha field is set to the value of the last call.
func (b *DryShaRecordApplyConfiguration) WithSha(value string) *DryShaRecordApplyConfiguration {
	b.Sha = &value
	return b
}

// WithMergeSha sets the MergeSha field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MergeSha field is set to the value of the last call.
func (b *DryShaRecordApplyConfiguration) WithMergeSha(value string) *DryShaRecordApplyConfiguration {
	b.MergeSha = &value
	return b
}

// WithSource sets the Source field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Source field is set to the value of the last call.
func (b *DryShaRecordApplyConfiguration) WithSource(value apiv1alpha1.DryShaRecordSource) *DryShaRecordApplyConfiguration {
	b.Source = &value
	return b
}

// WithMergedAt sets the MergedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MergedAt field is set to the value of the last call.
func (b *DryShaRecordApplyConfiguration) WithMergedAt(value v1.Time) *DryShaRecordApplyConfiguration {
	b.MergedAt = &value
	return b
}

// WithSuccessful sets the Successful field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Successful field is set to the value of the last call.
func (b *DryShaRecordApplyConfiguration) WithSuccessful(value bool) *DryShaRecordApplyConfiguration {
	b.Successful = &value
	return b
}
