/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.21. DO NOT EDIT.

package v1alpha1

// EnvironmentVerificationStatusApplyConfiguration represents a declarative configuration of the EnvironmentVerificationStatus type for use
// with apply.
//
// EnvironmentVerificationStatus mirrors an environment's ChangeTransferPolicy status.verification on
// the PromotionStrategy and adds Current for the change the environment is running right now when it
// is healthy on it. Current is composed at reconcile time rather than stored on the CTP because it
// is a claim about the present.
type EnvironmentVerificationStatusApplyConfiguration struct {
	// DryShas are copied from the owning ChangeTransferPolicy status.verification.dryShas: changes
	// this environment was healthy on when it promoted past them, newest first.
	DryShas []HealthyDryShasApplyConfiguration `json:"dryShas,omitempty"`
	// ObservedActiveSha is copied from the owning ChangeTransferPolicy status.verification.observedActiveSha.
	// Supports both SHA-1 (40 chars) and SHA-256 (64 chars) Git hash formats.
	ObservedActiveSha *string `json:"observedActiveSha,omitempty"`
	// Current is the change the environment is running right now when every active commit status is
	// passing and that change is not already in DryShas. Omitted when the environment is not healthy
	// on its active change or when the active change is already recorded in DryShas.
	Current *HealthyDryShasApplyConfiguration `json:"current,omitempty"`
}

// EnvironmentVerificationStatusApplyConfiguration constructs a declarative configuration of the EnvironmentVerificationStatus type for use with
// apply.
func EnvironmentVerificationStatus() *EnvironmentVerificationStatusApplyConfiguration {
	return &EnvironmentVerificationStatusApplyConfiguration{}
}

// WithDryShas adds the given value to the DryShas field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DryShas field.
func (b *EnvironmentVerificationStatusApplyConfiguration) WithDryShas(values ...*HealthyDryShasApplyConfiguration) *EnvironmentVerificationStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithDryShas")
		}
		b.DryShas = append(b.DryShas, *values[i])
	}
	return b
}

// WithObservedActiveSha sets the ObservedActiveSha field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedActiveSha field is set to the value of the last call.
func (b *EnvironmentVerificationStatusApplyConfiguration) WithObservedActiveSha(value string) *EnvironmentVerificationStatusApplyConfiguration {
	b.ObservedActiveSha = &value
	return b
}

// WithCurrent sets the Current field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Current field is set to the value of the last call.
func (b *EnvironmentVerificationStatusApplyConfiguration) WithCurrent(value *HealthyDryShasApplyConfiguration) *EnvironmentVerificationStatusApplyConfiguration {
	b.Current = value
	return b
}
