/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.21. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// PromotionCandidateStateApplyConfiguration represents a declarative configuration of the PromotionCandidateState type for use
// with apply.
//
// PromotionCandidateState summarizes the tip of the hydrator's proposed branch.
//
// It is deliberately a handful of scalars rather than a CommitBranchState. Only these fields are
// meaningful for a change that has not been selected for promotion, and CommitBranchState carries
// enough validated URL fields that repeating it here would push the CRDs a long way toward the
// apiserver's per-schema CEL cost limit (see hack/celcost/report.md) for information nothing reads.
type PromotionCandidateStateApplyConfiguration struct {
	// DrySha is the dry commit SHA this candidate hydrates, read from hydrator.metadata.
	// Supports both SHA-1 (40 chars) and SHA-256 (64 chars) Git hash formats.
	DrySha *string `json:"drySha,omitempty"`
	// HydratedSha is the commit SHA at the tip of the proposed branch.
	// Supports both SHA-1 (40 chars) and SHA-256 (64 chars) Git hash formats.
	HydratedSha *string `json:"hydratedSha,omitempty"`
	// CommitTime is the time of the hydrated commit.
	CommitTime *v1.Time `json:"commitTime,omitempty"`
	// NoteDrySha is the dry SHA from the git note on the hydrated commit, when there is one. It runs
	// ahead of DrySha after a hydration that changed no manifests, because the hydrator then updates
	// only the note and creates no new commit.
	// Supports both SHA-1 (40 chars) and SHA-256 (64 chars) Git hash formats.
	NoteDrySha *string `json:"noteDrySha,omitempty"`
}

// PromotionCandidateStateApplyConfiguration constructs a declarative configuration of the PromotionCandidateState type for use with
// apply.
func PromotionCandidateState() *PromotionCandidateStateApplyConfiguration {
	return &PromotionCandidateStateApplyConfiguration{}
}

// WithDrySha sets the DrySha field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DrySha field is set to the value of the last call.
func (b *PromotionCandidateStateApplyConfiguration) WithDrySha(value string) *PromotionCandidateStateApplyConfiguration {
	b.DrySha = &value
	return b
}

// WithHydratedSha sets the HydratedSha field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HydratedSha field is set to the value of the last call.
func (b *PromotionCandidateStateApplyConfiguration) WithHydratedSha(value string) *PromotionCandidateStateApplyConfiguration {
	b.HydratedSha = &value
	return b
}

// WithCommitTime sets the CommitTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CommitTime field is set to the value of the last call.
func (b *PromotionCandidateStateApplyConfiguration) WithCommitTime(value v1.Time) *PromotionCandidateStateApplyConfiguration {
	b.CommitTime = &value
	return b
}

// WithNoteDrySha sets the NoteDrySha field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NoteDrySha field is set to the value of the last call.
func (b *PromotionCandidateStateApplyConfiguration) WithNoteDrySha(value string) *PromotionCandidateStateApplyConfiguration {
	b.NoteDrySha = &value
	return b
}
