/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.21. DO NOT EDIT.

package v1alpha1

// PromotionCandidatesApplyConfiguration represents a declarative configuration of the PromotionCandidates type for use
// with apply.
//
// PromotionCandidates lists the changes a ChangeTransferPolicy is allowed to promote.
type PromotionCandidatesApplyConfiguration struct {
	// DryShas are the dry commit SHAs that every preceding environment has verified, newest first.
	// Only candidates whose dry SHA appears in this list may be promoted. An empty list means no
	// change is currently eligible, which is different from a nil PromotionCandidates (unconstrained).
	DryShas []string `json:"dryShas,omitempty"`
}

// PromotionCandidatesApplyConfiguration constructs a declarative configuration of the PromotionCandidates type for use with
// apply.
func PromotionCandidates() *PromotionCandidatesApplyConfiguration {
	return &PromotionCandidatesApplyConfiguration{}
}

// WithDryShas adds the given value to the DryShas field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DryShas field.
func (b *PromotionCandidatesApplyConfiguration) WithDryShas(values ...string) *PromotionCandidatesApplyConfiguration {
	for i := range values {
		b.DryShas = append(b.DryShas, values[i])
	}
	return b
}
