/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.21. DO NOT EDIT.

package v1alpha1

// VerificationStateApplyConfiguration represents a declarative configuration of the VerificationState type for use
// with apply.
//
// VerificationState is an environment's record of the changes it was healthy on when it stopped
// running them.
//
// It is a cache over git rather than an accumulated log: each promotion records the outgoing change's
// health in its merge commit on the active branch, so all of this can be rebuilt by walking that
// branch, and losing the status costs nothing permanent. It deliberately excludes the change the
// environment is running right now — that one has no merge commit yet and is judged on live health
// instead, wherever the record is consumed.
type VerificationStateApplyConfiguration struct {
	// DryShas are the dry commits this environment was healthy on at the point it promoted past them,
	// newest first and capped at MaxLastHealthyDryShas.
	DryShas []HealthyDryShasApplyConfiguration `json:"dryShas,omitempty"`
	// ObservedActiveSha is the active branch commit the git-derived entries were built from. While the
	// active branch still points there the walk is skipped entirely; when it has moved, only the
	// commits added since are examined.
	// Supports both SHA-1 (40 chars) and SHA-256 (64 chars) Git hash formats.
	ObservedActiveSha *string `json:"observedActiveSha,omitempty"`
}

// VerificationStateApplyConfiguration constructs a declarative configuration of the VerificationState type for use with
// apply.
func VerificationState() *VerificationStateApplyConfiguration {
	return &VerificationStateApplyConfiguration{}
}

// WithDryShas adds the given value to the DryShas field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DryShas field.
func (b *VerificationStateApplyConfiguration) WithDryShas(values ...*HealthyDryShasApplyConfiguration) *VerificationStateApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithDryShas")
		}
		b.DryShas = append(b.DryShas, *values[i])
	}
	return b
}

// WithObservedActiveSha sets the ObservedActiveSha field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedActiveSha field is set to the value of the last call.
func (b *VerificationStateApplyConfiguration) WithObservedActiveSha(value string) *VerificationStateApplyConfiguration {
	b.ObservedActiveSha = &value
	return b
}
