apiVersion: v1
kind: Service
metadata:
  name: promoter-aggregated-apiserver
  namespace: promoter-system
spec:
  ports:
  - port: 443
    targetPort: 8443
    protocol: TCP
  selector:
    app: promoter-aggregated-apiserver

