apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: promoter-system

resources:
  - deployment.yaml
  - service.yaml
  - apiservice.yaml
  - rbac.yaml
  - rbac-kube-system.yaml
